//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloServiceClient.SayHiServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SayHiServiceReference.ISayHiService")]
    public interface ISayHiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISayHiService/SayHi", ReplyAction="http://tempuri.org/ISayHiService/SayHiResponse")]
        string SayHi(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISayHiService/SayHi", ReplyAction="http://tempuri.org/ISayHiService/SayHiResponse")]
        System.Threading.Tasks.Task<string> SayHiAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISayHiServiceChannel : HelloServiceClient.SayHiServiceReference.ISayHiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SayHiServiceClient : System.ServiceModel.ClientBase<HelloServiceClient.SayHiServiceReference.ISayHiService>, HelloServiceClient.SayHiServiceReference.ISayHiService {
        
        public SayHiServiceClient() {
        }
        
        public SayHiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SayHiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SayHiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SayHiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHi(string name) {
            return base.Channel.SayHi(name);
        }
        
        public System.Threading.Tasks.Task<string> SayHiAsync(string name) {
            return base.Channel.SayHiAsync(name);
        }
    }
}
